// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Location  string
	Landmark  string
	City      string
	Country   string
	Pin       int32
	Userid    uuid.UUID
}

type Cart struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Numitemsincart int32
	Chargetotal    float64
	Shipping       int32
	Tax            float64
	Ordertotal     int32
	Userid         uuid.UUID
}

type Cartproduct struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Amount    int32
	Cartid    uuid.UUID
	Productid uuid.UUID
}

type Order struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Ordertotal float64
	Userid     uuid.UUID
	Addressid  uuid.UUID
}

type Orderproduct struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Amount    int32
	Orderid   uuid.UUID
	Productid uuid.UUID
}

type Product struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Price       int32
	Image       string
	Company     string
	Description string
	Category    string
	Featured    bool
	Shipping    bool
	Visits      int32
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Role      string
	Email     string
	Password  string
}
