// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Numitemsincart int32
	Chargetotal    float64
	Shipping       int32
	Tax            float64
	Ordertotal     int32
	Userid         uuid.UUID
}

type Cartproduct struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Amount    int32
	Cartid    uuid.UUID
	Productid uuid.UUID
}

type Product struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Price       int32
	Image       string
	Company     string
	Description string
	Category    string
	Featured    bool
	Shipping    bool
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Role      string
	Email     string
	Password  string
}
