// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: products.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createProduct = `-- name: CreateProduct :one
insert into products(id, created_at, updated_at, name, price, image, description, category, company, featured, shipping)
values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, created_at, updated_at, name, price, image, company, description, category, featured, shipping, visits
`

type CreateProductParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Price       int32
	Image       string
	Description string
	Category    string
	Company     string
	Featured    bool
	Shipping    bool
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Price,
		arg.Image,
		arg.Description,
		arg.Category,
		arg.Company,
		arg.Featured,
		arg.Shipping,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Price,
		&i.Image,
		&i.Company,
		&i.Description,
		&i.Category,
		&i.Featured,
		&i.Shipping,
		&i.Visits,
	)
	return i, err
}

const getAllProducts = `-- name: GetAllProducts :many
select id, created_at, updated_at, name, price, image, company, description, category, featured, shipping, visits from products
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Price,
			&i.Image,
			&i.Company,
			&i.Description,
			&i.Category,
			&i.Featured,
			&i.Shipping,
			&i.Visits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompanyAndCategory = `-- name: GetCompanyAndCategory :many
select distinct company,category from products
`

type GetCompanyAndCategoryRow struct {
	Company  string
	Category string
}

func (q *Queries) GetCompanyAndCategory(ctx context.Context) ([]GetCompanyAndCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getCompanyAndCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompanyAndCategoryRow
	for rows.Next() {
		var i GetCompanyAndCategoryRow
		if err := rows.Scan(&i.Company, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeaturedProducts = `-- name: GetFeaturedProducts :many
select id, created_at, updated_at, name, price, image, company, description, category, featured, shipping, visits from products
where featured = true
`

func (q *Queries) GetFeaturedProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getFeaturedProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Price,
			&i.Image,
			&i.Company,
			&i.Description,
			&i.Category,
			&i.Featured,
			&i.Shipping,
			&i.Visits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilteredProducts = `-- name: GetFilteredProducts :many
select id, created_at, updated_at, name, price, image, company, description, category, featured, shipping, visits from products
where (name like $1)
and (price < $2)
and (company = any($3::text[]))
and (category = any($4::text[]))
limit $5
offset $6
`

type GetFilteredProductsParams struct {
	Name    string
	Price   int32
	Column3 []string
	Column4 []string
	Limit   int32
	Offset  int32
}

func (q *Queries) GetFilteredProducts(ctx context.Context, arg GetFilteredProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getFilteredProducts,
		arg.Name,
		arg.Price,
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Price,
			&i.Image,
			&i.Company,
			&i.Description,
			&i.Category,
			&i.Featured,
			&i.Shipping,
			&i.Visits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilteredProductsComanyandCategory = `-- name: GetFilteredProductsComanyandCategory :many
select distinct company,category from products
where (name like $1)
and (price < $2)
and (company = any($3::text[]))
and (category = any($4::text[]))
`

type GetFilteredProductsComanyandCategoryParams struct {
	Name    string
	Price   int32
	Column3 []string
	Column4 []string
}

type GetFilteredProductsComanyandCategoryRow struct {
	Company  string
	Category string
}

func (q *Queries) GetFilteredProductsComanyandCategory(ctx context.Context, arg GetFilteredProductsComanyandCategoryParams) ([]GetFilteredProductsComanyandCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilteredProductsComanyandCategory,
		arg.Name,
		arg.Price,
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilteredProductsComanyandCategoryRow
	for rows.Next() {
		var i GetFilteredProductsComanyandCategoryRow
		if err := rows.Scan(&i.Company, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilteredProductsCount = `-- name: GetFilteredProductsCount :one
select count(*) from products
where (name like $1)
and (price < $2)
and (company = any($3::text[]))
and (category = any($4::text[]))
`

type GetFilteredProductsCountParams struct {
	Name    string
	Price   int32
	Column3 []string
	Column4 []string
}

func (q *Queries) GetFilteredProductsCount(ctx context.Context, arg GetFilteredProductsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFilteredProductsCount,
		arg.Name,
		arg.Price,
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductById = `-- name: GetProductById :one
select id, created_at, updated_at, name, price, image, company, description, category, featured, shipping, visits from products
where id = $1
`

func (q *Queries) GetProductById(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Price,
		&i.Image,
		&i.Company,
		&i.Description,
		&i.Category,
		&i.Featured,
		&i.Shipping,
		&i.Visits,
	)
	return i, err
}

const getVisitsOfProducts = `-- name: GetVisitsOfProducts :many
select id,name,visits from products
`

type GetVisitsOfProductsRow struct {
	ID     uuid.UUID
	Name   string
	Visits int32
}

func (q *Queries) GetVisitsOfProducts(ctx context.Context) ([]GetVisitsOfProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getVisitsOfProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVisitsOfProductsRow
	for rows.Next() {
		var i GetVisitsOfProductsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Visits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementProductVisitById = `-- name: IncrementProductVisitById :exec
update products
set updated_at = NOW(),
visits = visits + 1
where id = $1
`

func (q *Queries) IncrementProductVisitById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementProductVisitById, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
update products
set updated_at = NOW(),
name = $1,
price = $2,
description = $3,
company = $4,
category = $5,
image = $6,
featured = $7,
shipping = $8
where id = $9
RETURNING id, created_at, updated_at, name, price, image, company, description, category, featured, shipping, visits
`

type UpdateProductParams struct {
	Name        string
	Price       int32
	Description string
	Company     string
	Category    string
	Image       string
	Featured    bool
	Shipping    bool
	ID          uuid.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Name,
		arg.Price,
		arg.Description,
		arg.Company,
		arg.Category,
		arg.Image,
		arg.Featured,
		arg.Shipping,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Price,
		&i.Image,
		&i.Company,
		&i.Description,
		&i.Category,
		&i.Featured,
		&i.Shipping,
		&i.Visits,
	)
	return i, err
}
