name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build app
        run: ./scripts/buildprod.sh

      - name: Build Docker image
        run: docker build -t gcr.io/ecom1-423115/ecom1-ar-repo/ecom1:latest .

      # Add the migration step here
      - name: Run DB migrations
        run: ./scripts/migrateup.sh
        env:
          DB_CONN: ${{ secrets.DB_CONN }}

      
      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ecom1-423115

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Push Docker image to GCR
        run: docker push gcr.io/ecom1-423115/ecom1-ar-repo/ecom1:latest

      - name: Deploy to Cloud Run
        run: gcloud run deploy ecom1 --image gcr.io/ecom1-423115/ecom1-ar-repo/ecom1:latest --region us-central1 --allow-unauthenticated --project ecom1-423115 --max-instances=4